CREATE TABLE category
  (
     id          IDENTITY,
     name        VARCHAR(50),
     description VARCHAR(255),
     image_url   VARCHAR(50),
     active_ind  BOOLEAN,
     CONSTRAINT pk_category_id PRIMARY KEY (id)
  );   
  
  INSERT INTO category(name,description,image_url,active_ind) VALUES ('Laptop','This is description of Laptop','CAT_1.png',true);
  INSERT INTO category(name,description,image_url,active_ind) VALUES ('Mobile','This is description of Mobile','CAT_2.png',true);
  INSERT INTO category(name,description,image_url,active_ind) VALUES ('Television','This is description of tv','CAT_3.png',true);
  
  CREATE TABLE user_detail
  (
     id             IDENTITY,
     first_name     VARCHAR(50),
     last_name      VARCHAR(50),
     ROLE           VARCHAR(50),
     active_ind     BOOLEAN,
     password       VARCHAR(50),
     email          VARCHAR(100),
     contact_number VARCHAR(12),
     CONSTRAINT pk_user_id PRIMARY KEY (id)
  );  
  
  INSERT INTO user_detail (first_name, last_name ,role,active_ind ,password, email ,contact_number) 
                   VALUES ('RAMESH','ARVIND','ADMIN',true,'admin','ramesh.arvind@gmail.com','9004800912');
  INSERT INTO user_detail (first_name, last_name ,role,active_ind ,password, email ,contact_number) 
                   VALUES ('PRAKASH','RAJ','SUPPLIER',true,'12345','prakash.raj@gmail.com','9004800914');  
  INSERT INTO user_detail (first_name, last_name ,role,active_ind ,password, email ,contact_number) 
                   VALUES ('ARJUN','RAMPAL','SUPPLIER',true,'12345','arjun.rampal@gmail.com','9004800916');                  
                   
 
 CREATE TABLE product
  (
     id          IDENTITY,
     code        VARCHAR(50),
     name        VARCHAR(50),
     brand       VARCHAR(50),
     description VARCHAR(255),
     unit_price  DECIMAL (10, 2),
     quantity    INT,
     active_ind  BOOLEAN,
     category_id INT,
     supplier_id INT,
     purchases   INT DEFAULT 0,
     views       INT DEFAULT 0,
     CONSTRAINT pk_product_id PRIMARY KEY (id),
     CONSTRAINT fk_category_id FOREIGN KEY (category_id) REFERENCES category (id),
     CONSTRAINT fk_supplier_id FOREIGN KEY (supplier_id) REFERENCES user_detail (id)
  );                    
             
 INSERT INTO product (code,name, brand, description, unit_price, quantity, active_ind ,category_id ,supplier_id) VALUES
 ('PRDABC123DEFX','iPhone X','Apple','Built in Voice Recorder',32000,12,true,2,2);
 
 INSERT INTO product (code,name, brand, description, unit_price, quantity, active_ind ,category_id ,supplier_id) VALUES
 ('PRDABZ123DEFX','PULSE IX','VIDEOCON','Built in GPS MAP',17000,34,true,2,2);
 
 INSERT INTO product (code,name, brand, description, unit_price, quantity, active_ind ,category_id ,supplier_id) VALUES
 ('PRDABY123DEFX','MI NOTE 5','Xiomi','Built in Video Recorder',12000,72,true,2,3);
 
  INSERT INTO product (code,name, brand, description, unit_price, quantity, active_ind ,category_id ,supplier_id) VALUES
 ('PRDAWY123DEFX','THUNDER','ONIDA','CURVED SCREEN',42000,32,true,3,3);
 
  INSERT INTO product (code,name, brand, description, unit_price, quantity, active_ind ,category_id ,supplier_id) VALUES
 ('PRDQBY123DEFX','BRAVIA','SONY','HD video',72000,23,true,3,2);
 
  INSERT INTO product (code,name, brand, description, unit_price, quantity, active_ind ,category_id ,supplier_id) VALUES
 ('PRDQBY123DESX','LENOVO SLIM','LENOVO','HIGH PERFORMANCE',72000,21,true,1,2);
 
  INSERT INTO product (code,name, brand, description, unit_price, quantity, active_ind ,category_id ,supplier_id) VALUES
 ('PRDQBY133DEFW','INSPIRON','DELL','GOOD DESIGN',82000,13,true,1,3);
 
 
 create table Address (
       id integer generated by default as identity,
        address_line_one varchar(255),
        address_line_two varchar(255),
        billing boolean not null,
        city varchar(255),
        country varchar(255),
        postal_code varchar(255),
        shipping boolean not null,
        state varchar(255),
        user_id integer,
        primary key (id)
    );

    
    create table Cart (
       id integer generated by default as identity,
        cart_lines integer,
        grand_total double,
        user_id integer,
        primary key (id)
    );

    
    create table Category (
       id bigint generated by default as identity,
        active_ind boolean,
        description varchar(255),
        name varchar(255),
        primary key (id)
    );

    
    create table Product (
       id integer generated by default as identity,
        active_ind boolean,
        brand varchar(255),
        category_id integer,
        code varchar(255),
        description varchar(255),
        name varchar(255),
        purchases integer,
        quantity integer,
        supplier_id integer,
        unit_price double,
        views integer,
        primary key (id)
    );

    
    create table Users (
       id integer generated by default as identity,
        active_ind boolean,
        contact_number varchar(255),
        email varchar(255),
        first_name varchar(255),
        last_name varchar(255),
        password varchar(255),
        role varchar(255),
        primary key (id)
    );
    
    insert 
    into
        Users
        (id, active_ind, contact_number, email, first_name, last_name, password, role) 
    values
        (null, ?, ?, ?, ?, ?, ?, ?);
		
	insert 
    into
        Address
        (id, address_line_one, address_line_two, billing, city, country, postal_code, shipping, state, user_id) 
    values
        (null, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    insert 
    into
        Cart
        (id, cart_lines, grand_total, user_id) 
    values
        (null, ?, ?, ?)		;
        
        
        
CREATE TABLE cart_line 
  ( 
     id            IDENTITY, 
     cart_id       INT, 
     total         DECIMAL(10, 2), 
     product_id    INT, 
     product_count INT, 
     buying_price  DECIMAL(10, 2), 
     active_ind    BOOLEAN, 
     CONSTRAINT fk_cart_line_cart_id FOREIGN KEY (cart_id) REFERENCES cart (id), 
     CONSTRAINT fk_cart_line_product_id FOREIGN KEY (product_id) REFERENCES  product(id), 
     CONSTRAINT fk_cart_line_id PRIMARY KEY (id) 
  );      
 
 
 
 
 
 
 
 
 
 
                   
  